### ISSUE TITLE
Logger class

### ISSUE THREAD

**Issue by dooks** [dooks/stacks-overflow-group#23]
Create an ease of use logging class

e.g.:

``` cpp
    Log log("filename.log");
    ... (somework)
    log << "Sold book for " << price << endl;
```

This will require operator overloading of `<<`

**Comment by bobthewalrus** [comment]
Every time i read this i get confused. I'll be happy to help, i'm just not sure of what it is you want exactly here.

**Comment by bobthewalrus** [comment]
We should probably discuss this tomorrow.

**Comment by dooks** [comment]
Time restriction. Not necessary, should have made this from the start.
