### ISSUE TITLE
Find library

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#24]
The library I made disappeared. Or I never pushed it properly.

**Comment by dooks** [comment]
A mistake I did a lot when I first started github was I committed the changes, but forgot to push?

Did you switch to a new branch after you made the library? Try switching back to the old one. Whenever you actually run a commit, the local git repo remembers all the changes (it just doesn't show up on the website if you don't push it)

**Comment by bobthewalrus** [comment]
I see what I've done, unfortunately I won't be able to fix it until I get
back home.
