### ISSUE TITLE
Pseudocode for Cashier module

### ISSUE THREAD

**Issue by dooks** [dooks/stacks-overflow-group#3]
Stick it all in `cashier.h`, and make an empty file for `cashier.cpp`

[edit] After looking over the required project deliverables, it's best if we do a UML diagram instead to start off.

**Comment by bobthewalrus** [comment]
Should be done.

**Comment by dooks** [comment]
All right that looks good. I'm going to rebase the commits into one, then push the branch. We'll be ready to move onto the next milestone shortly.
