### ISSUE TITLE
ifndef/define statements for date.h and book.h

### ISSUE THREAD

**Issue by lyalfred** [dooks/stacks-overflow-group#51]
Isn't it necessary to include 
# ifndef DATE_H
# define DATE_H

{
};
# endif

**Comment by lyalfred** [comment]
Nevermind I figured out what #pragma once does lol. 
Do you think Goel will be okay with that notation? I don't know if we covered it in class...

**Comment by dooks** [comment]
I think so. The `#ifndef DATE_H` include guards were a C thing. `#pragma once` was introduced in C++ so I thought it would be appropriate for the class lol.

I think there are a few differences, but I actually do think the C include guards are safer. If you think we should use those instead I don't mind changing them at all.
