### ISSUE TITLE
subtotal retrieve retailprice

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#52]
Cashier function for subtotal, i'm stumped.
looks like:
double Cashier::getSubTotal(Book\* book){
    /*
    if book is in cart list, add retail price to subtotal
    return subtotal
    */
    double subtotal = 0;
    for (unsigned i = 0; i < m_cartlist.size(); i++)
    {
        if (book == m_cartlist[i]) {
???
???getRetailPrice(i) += subtotal;???
Book::getRetailPrice() = temp;
Book.getRetailPrice() = temp;

???
        }
    }

```
return subtotal;
```

}

**Comment by dooks** [comment]
You could have formatted this a bit better to make it easier to read. :) Github uses Markdown for formatting. I think this is what you are trying to do?

``` cpp
double Cashier::getSubTotal(Book* book){
    /*
    if book is in cart list, add retail price to subtotal
    return subtotal
    */
    double subtotal = 0;
    for (unsigned i = 0; i < m_cartlist.size(); i++)
    {
        if (book == m_cartlist[i])
        {
            // If book matches item in list, this item's subtotal is added
            subtotal += m_cartlist[i]->getRetailPrice();
        }
    }

    return subtotal;
}
```

**Comment by bobthewalrus** [comment]
Great, thanks!
Sorry, I just copy-pasted from visual studio. Is there a way I can format it nicely from VS or would I have to upload to GitHub first?

**Comment by dooks** [comment]
No, you have to manually format it once you paste it in. :o Only should take an extra minute once you learn most of the markdown rules...... buuuuut it's really not important. Glad to know I fixed your problem. :)

https://guides.github.com/features/mastering-markdown/
