### ISSUE TITLE
Dumb question #3

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#54]
Cleaning up cashiermenu.cpp
and I can't come up with the proper context to call the functions I've created in cashier.h
for example, findISBN
cout << "Please enter the ISBN: " << endl;
        cin >> isbn;
        vector<Book*>findISBN(isbn);
which is definitely not correct.
so is 
        Cashier::findISBN(isbn);

**Comment by dooks** [comment]
You have to make an instance of Cashier first (since it's an object)

e.g.

``` cpp
    /// Beginning of the program
    Inventory inv;
    Cashier cashier(&inv);

    ...

    // Somewhere later in the program when you need to do work and shit
    cashier.findISBN(isbn);
```

**Comment by dooks** [comment]
Class == Object == datatype

When we defined the class, we defined a template for any instances that are made of the class type.

``` cpp
    Class Cashier {
    public:
    Cashier(Inventory* inv);
        int examplevar;
        int examplevar2;
        // etc ...
    };
```

Now whenever you make an object of that class, you can access those members with the . operator.

``` cpp
    Cashier cashier(&inv);
    int x = cashier.examplevar;
    int y = cashier.examplevar2;
```

**Comment by bobthewalrus** [comment]
got it! thanks again!
but leads me right to the next problem. now that i've searched, i need to display the books that came up.
will this require an iterator?

**Comment by dooks** [comment]
You just need to loop through the array/vector that it returns.

``` cpp
    // example of an vector<int>
    vector<int> int_list;

    // We put some elements into i, so it has shit in it
    for(unsigned i = 0; i < int_list.size(); i++)  {
        cout << int_list[i] << endl;
    }
```

So apply that to a `vector<Book*>`

**Comment by bobthewalrus** [comment]
So that for loop creates a vector holding each of the ISBN numbers in a slot, and then displays them one by one, how do i access the rest of the book's information via these methods?
namely isbn, title, author, and price.

``` cpp
#include "inventory.h"
#include "Cashier.h"

#include <iostream>
#include <string>
using namespace std;
int main()
{
    Inventory inv;
    Cashier cash(&inv);

    string userisbn;
    cout << "Let's try this.";
    cout << "Please enter the ISBN: " << endl;
    cin >> userisbn;
    cout << userisbn << endl;

    cash.findISBN(userisbn);
    for (unsigned i = 0; i < userisbn.size(); i++)  {
        cout <<userisbn[i] << endl;
    }

    system("pause");
}
```

**Comment by dooks** [comment]
`userisbn[i]` is the `Book*` because `userisbn` is an array, or vector, of `Book*`

``` cpp
     userisbn[i]->getTitle();
```

**Comment by bobthewalrus** [comment]
That gives me an error
"error: expression must have pointer type."
userisbn[i].getTitle();
gives me the error expression must have class type

**Comment by dooks** [comment]
Oh sorry. I didn't see earlier. userisbn is a string you declared earlier, not the vector/array. When you call findISBN, it returns a vector you need to save to something.

``` cpp
    vector<Book*> isbnlist = cash.findISBN(userisbn);
    for (unsigned i = 0; i < isbnlist.size(); i++)  {
        cout << isbnlist[i]->getTitle(); << endl;
    }
```

**Comment by bobthewalrus** [comment]
brilliant.

**Comment by bobthewalrus** [comment]
While this seems to work, try as I might, I can't pull up any info from the inventory, it looks like the for loop never even runs. 

``` cpp
#include "inventory.h"
#include "Cashier.h"
#include "db.h"
#include "book.h"
#include "date.h"

#include <iostream>
#include <string>
using namespace std;
int main()
{
    Inventory inv;
    Cashier cash(&inv);
    string userisbn;

    cout << "Let's try this.";
    cout << "Please enter the ISBN: " << endl;
    std::getline(std::cin, userisbn);
    cout << userisbn << endl;

    vector<Book*> isbnlist =cash.findISBN(userisbn);
    for (unsigned i = 0; i < isbnlist.size(); i++)  {
        cout << i;
        cout << "What the fuck";
        cout <<isbnlist[i]->getTitle()<< endl;
        cout << isbnlist[i]->getISBN() << endl;
        cout << isbnlist[i]->getAuthor() << endl;
        cout << isbnlist[i]->getRetailPrice() << endl;
    }
    cout << "whatthefuck";
    system("pause");
}
```

This will output whatever I type followed by whatthefuck
adding cout << isbnlist.size() 
returns 0, every time.

I don't know if it will help, but for this test, I created a new project, only including the .h and .cpp files:
book, cashier, date, db, and inventory, and then a main.cpp

**Comment by dooks** [comment]
You maybe forgot to call inv.reset() after you declared it. If you look in the debugger, `inv` is completely empty.

**Comment by bobthewalrus** [comment]
Do i need to add the library binary file??

**Comment by dooks** [comment]
Yeah if you cloned it, there should be a `books.db` file in tools which is where it reads from.

**Comment by bobthewalrus** [comment]
Damn I still can't get it to test correctly on my machine.
Thanks a ton for the partial search

**Comment by bobthewalrus** [comment]
FUCKYESIGOTITOMFGITFINALLYDOESSOMETHINGZOMG

**Comment by dooks** [comment]
Try using the debugger to check what is getting passed? This is what worked for me

``` cpp
    #include "inventory.h"
    #include "Cashier.h"
    #include "db.h"
    #include "book.h"
    #include "date.h"

    #include <iostream>
    #include <string>
    using namespace std;

    int main()
    {
        Inventory inv;
        inv.reset();
        Cashier cash(&inv);
        string userisbn = "9";

        vector<Book*> isbnlist = cash.findISBN(userisbn);
        for (unsigned i = 0; i < isbnlist.size(); i++)  {
            cout << i;
            cout << "What the fuck";
            cout <<isbnlist[i]->getTitle()<< endl;
            cout << isbnlist[i]->getISBN() << endl;
            cout << isbnlist[i]->getAuthor() << endl;
            cout << isbnlist[i]->getRetailPrice() << endl;
        }
        cout << "whatthefuck";
        system("pause");
    }
```
