### ISSUE TITLE
need default constructor for report and cashier modules

### ISSUE THREAD

**Issue by lyalfred** [dooks/stacks-overflow-group#61]
kept getting compile error: "C2512: 'Report' : no appropriate default constructor available"

error was fixed when default constructors were added on my files. Just a head's up

**Comment by lyalfred** [comment]
deconstructions as well.

**Comment by dooks** [comment]
Report constructor requires a pointer or an address to an Inventory object to function (I had to change it in order for the reports to run correctly). Don't add in default constructors.

**Comment by bobthewalrus** [comment]
running into this issue myself, what's the solution here then, when instantiating cashier or report?
cashier cash;

is not the answer, 
cashier &cash;?

**Comment by bobthewalrus** [comment]
is it cashier &cash=cash;
??
sorry just trying different things and that seemed to work

**Comment by dooks** [comment]
``` cpp
    Inventory inv;
    Cashier cash(&inv);
    Report report(&inv);
```

**Comment by bobthewalrus** [comment]
thanks!
