### ISSUE TITLE
Exception handling encountered

### ISSUE THREAD

**Issue by lyalfred** [dooks/stacks-overflow-group#62]
Unhandled exception at 0x00B6B5A9 in Bookstore3-12-15.exe: 0xC0000005: Access violation reading location 0x00000008.

**Comment by dooks** [comment]
Instead of hitting "Abort" or "Break" when this occurs, hit "Retry". It will stop at the line the exception occurs

**Comment by dooks** [comment]
Also check the output, I set it to print to screen when exceptions occur

**Comment by bobthewalrus** [comment]
Same bug, don't see a solution here. Line I'm getting the exception at is in cashier.cpp
vector<Book*> isbnsearch = inv->findBook(Book::ISBN, &userisbn);

**Comment by bobthewalrus** [comment]
Nevermind got mine to work.
