### ISSUE TITLE
Adding to cart

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#67]
I may be confused in the way AddCart works in Cashier.h
can pull up list of searched books fine, attempting to allow user to add a book to cart. code looks like:

``` cpp
void MainMenu::CashMenuISBN(string)
{
    cout << "Please enter the ISBN: " << endl;
    cin.clear();
    fflush(stdin);
    std::getline(std::cin, userisbn);

    //function call to search for isbn
    cout << "   ISBN            Title               Author            Price " << endl;
    vector<Book*> isbnlist = cash.findISBN(userisbn);
    for (unsigned i = 0; i < isbnlist.size(); i++)  {
        cout << "";
        cout <<i+1<<". "<< isbnlist[i]->getISBN() << "    " 
            << isbnlist[i]->getTitle() << "     ";
        cout << isbnlist[i]->getAuthor() << "     $"
            << isbnlist[i]->getRetailPrice() << endl;

    }
    cout << "Please type the number of the selection you'd like to add to your cart:" << endl;
    cin >> cartchoice;
    for (unsigned i = 0; i < isbnlist.size(); i++) {
        if (cartchoice==i)
        { 
            cash.addCart(Book);
        }
    }

    //cout << 1. \n 2. \n  3. \n 4. \n 5. vector search results=true
    //Please type the number of the selection you'd like to make.

}
```

cash.addCart(Book); is where I encounter errors, and may be implemented incorrectly altogether.

**Comment by dooks** [comment]
`cash.addCart(Book)` is wrong because `Book` is the name of the class. The required argument is a `Book*` (book pointer)

Btw you're doing a good job documenting issues and updating the workable code on the dev branch. ^^

**Comment by bobthewalrus** [comment]
cash.addCart(Book*) does not work either. And should I be creating another vector, the cart vector for this situation?

**Comment by dooks** [comment]
You need to supply a book pointer to it, so you must already have it assigned as a variable.

``` cpp
    vector<Book*> small_list = inv.getRange(0, 5);
    Book* book = small_list[0];
    cash.addCart(book);            // We assigned a pointer to book, so we can use that
    cash.addCart(small_list[1]); // small_list[1] also works because it's also a book pointer
```

Also this is the logic we wrote for Cashier, as you can see we already made a vector for the cart.

``` cpp
    bool Cashier::addCart(Book* book) {
    /*
    Add book to cart list
        */
        m_cartlist.push_back(book);
        return true;
    }
```

**Comment by bobthewalrus** [comment]
I'm thoroughly confused by this.
here's what I've got, but it's certainly wrong.

``` cpp
cout << "Please type the number of the selection you'd like to add to your cart:" << endl;
    cin >> cartchoice;
    vector <Book*> cart = inv.getRange(0,5);

    Book* book = cart[cartchoice];
    for (unsigned i = 0; i < isbnlist.size(); i++) {
        if (cartchoice == i)
        {

    cash.addCart(book);

        }
    }
    cout << cartchoice << endl;
    for (unsigned i = 0; i < cart.size(); i++)  {
        cout << "";
        cout << i + 1 << ". " << cart[i]->getISBN() << "    "
            << cart[i]->getTitle() << "     ";
        cout << cart[i]->getAuthor() << "     $"
            << cart[i]->getRetailPrice() << endl;

    }
    cout << "Your selection has been added to your cart" << endl;
    //cout << 1. \n 2. \n  3. \n 4. \n 5. vector search results=true
    //Please type the number of the selection you'd like to make.

}
```

I think you were just trying to show me an example, but the first line with the getRange is throwing me off really bad, when only one selection should ever be added to the cart at a time.

**Comment by bobthewalrus** [comment]
/play secret 
will this work?

**Comment by dooks** [comment]
Well how are we getting to this screen? What is bringing up the user's selection? I don't have any context past this. o.o

You're also allowed to modify the cashier header file. Looking it over again, we have no way to access the cart inside of the class. So we're gonna need a displayCart method in Cashier, where it displays the internal `m_cartList`

**Comment by bobthewalrus** [comment]
So, for context, I've got a functional main menu that can bring up the various submenus. When I search via isbn the searched for books come up correctly, and then I was hoping to prompt the user to which of the results they would like to add to their cart.
As I understand it, there is, of course, a vector(1) holding the entire inventory's data.
Searching via isbn or one of our other options should create a second, much smaller vector(2).
And adding to cart should create, or add to another vector(3) at most one item at a time.
Have I got all that correct?
Is push_back book still the correct way? I mean, if I can get this done via the menu I'm happy with that.
Ideally, the user would select from their list of books displayed(2) which item to add to cart(3).
Their selection would become the int that is passed to the second vector(2), and the only selection from that vector which makes it to the cart(3).
I can't tell if what I said is really obvious or really confusing, so if you get a chance, I'd love to talk in some kinda realtime chat way.

**Comment by dooks** [comment]
Currently in math class. I won't be available for realtime chat till about 10pm.

Also, editing this comment to answer your questions, gimme a sec.

**Comment by bobthewalrus** [comment]
Appreciate it. I'll be here.

**Comment by dooks** [comment]
You've got points 1 and 2 completely correct, yes. Search returns a vector, a copy of a small slice of the entire inventory. Each item in the vector is a Book*.

For 3, yes, it also adds to the vector internal to Cashier (m_cartList). You don't make a new vector for this one, because `addCart(Book* book)` only returns a true or false. You only need to supply a `Book*` to the function.

Here's what I think you want to do (from what you said):
- Searches for a term, and saves that search into a vector
- After displaying that vector (and the user can enter in a number corresponding to the books display)
- Use that selection to addCart

You've got everything except for the third one, I'm seeing what you're getting at now. So in this case, `cartchoice` is the selection the user made, so you would just have to do

```
    vector<Book*> search = inv.findISBN("1"); // Find all ISBNs with a 1 in them
    int userchoice;
    // User makes choice, save that input into userchoice
    cash.addCart(search[userchoice]);
```

**Comment by bobthewalrus** [comment]
Alllllriiiight!
:metal:
Still have to find a way to test that one, but that definitely seems more like what I was looking for.
I'll try to make my questions more clear in the future.
:smile:
