### ISSUE TITLE
Menu Scope Outwards

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#70]
This is where I may have really goofed with the overall menu structure.
The menu's should pop back to a certain other menu once finished with whatever is you're doing.
For example, after adding a book to my cart, I want to see a confirmation, push enter, and then be returned to the cashier menu.
However, if you take a look at the structure, these starting menus are found in a switch statement in int main()
while all the other more specific menus are in their own void functions
there must be a way, but how do I pop back to menus in main?
I would copy paste, but it's really the entire structure of mainmenu.cpp that I'm speaking of, specifically, the int main() switches to different menu functions, and then some way of making the last line in just about all the other functions outside of main call back to one of those.

**Comment by bobthewalrus** [comment]
Fixed.

**Comment by dooks** [comment]
We should probably switch over the design to a state based UI since we have nested menus. This will actually take me some time to explain and give an example, which I'll be able to do once I'm home.

and ohokay. You just fixed it while I was typing this lol. I was going to provide this example  https://github.com/dooks/employee-management/blob/master/main.cpp

**Comment by bobthewalrus** [comment]
Its not fixed i lied

**Comment by bobthewalrus** [comment]
I know what you have there is probably the right answer, but we're getting behind on this whole thing. If you don't think it'll take much time to implement, or there's no sort of workaround for the problem I've coded into, then I'll gladly do it, but at this point I still don't see that light at the end of the tunnel marking the end of the project, and demos are supposed to be tomorrow!

**Comment by bobthewalrus** [comment]
It's not so much "we're getting behind" as it is I'm behind.

**Comment by dooks** [comment]
They're due Thursday : p

**Comment by dooks** [comment]
We'll have all class tomorrow to do them, there is no more lecture. I forgot you missed last class o.o

**Comment by bobthewalrus** [comment]
oh shoot sounds good

**Comment by dooks** [comment]
If you'd like, I wouldn't mind drilling up a state-based UI prototype that you guys can flesh out. I'm not going to lie, I really could have done this whole project myself xD But I want you guys to get your fair share of work to the best of your abilities

**Comment by dooks** [comment]
I really don't see a problem with all of this getting done by the end of tomorrow, but I would also like to meet up Wednesday to prepare for our presentation
