### ISSUE TITLE
You can't make me!

### ISSUE THREAD

**Issue by bobthewalrus** [dooks/stacks-overflow-group#71]
Is this label for when you're feeling bratty and don't want to fix something you messed up?

**Comment by dooks** [comment]
I suppose so! They're the default labels Github provides :p

**Comment by bobthewalrus** [comment]
realtime chat?

**Comment by bobthewalrus** [comment]
facebook or you got something better?

**Comment by dooks** [comment]
In a bit. I'm about to head home in about 10-20 minutes

**Comment by dooks** [comment]
Skype or facebook is okay

**Comment by bobthewalrus** [comment]
Sorry. _puts on patient hat_
